### ISSUE TITLE
Fail to verify the signature with API of mbedtls 

### ISSUE THREAD

**Issue by WeboFingerprints** [russhousley/pyhsslms#13]
Hi Russ,

Is this compatible with the LMS crypto signature in mbeldTLS 3.6.1? I am using pyhsslms.HssLmsPrivateKey.sign() with level 1 to get a signature of 1456 bytes and the public keys. But I cannot get the signature to be verified with mbedtls_lms_verify() after importing the public keys and signature in Mbedtls.

**Comment by WeboFingerprints** [comment]
I am using the types of pyhsslms.lms_sha256_m32_h10 and pyhsslms.lmots_sha256_n32_w8, which match the setting requirements as in Mbedtls.

**Comment by WeboFingerprints** [comment]
It is fixed. This is my fault in inserting keys into mbedtls APIs.

**Comment by russhousley** [comment]
I'm glad to hear that the two are compatible.
