### ISSUE TITLE
genkey test --levels=3 --lms=15 --lmots=1 --alg=sha256 --trunc=32

### ISSUE THREAD

**Issue by sebastien-riou** [russhousley/pyhsslms#6]
This is failing because it supports 0x200000000000 signatures and genkey tries to write this number as a 32 bit value in the private key file.

Questions:
- I did not find a specific file format in NIST documents nor in rfc8554, do you confirm that the file format is 'custom' rather than 'standardized' ?
- Fixing that 'cleanly' would mean changing the file format for private keys. Do you see an issue with that ?

stack trace using [my fork](https://github.com/sebastien-riou/pyhsslms/commit/8c587ca43c495a94fd9ddebf5451fd1feefa98a5)
```
$ python -m pyhsslms.hsslms genkey test --levels=3 --lms=15 --lmots=1 --alg=sha256 --trunc=32
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\_shared\repos\pyhsslms\pyhsslms\hsslms.py", line 264, in <module>
    main()
  File "C:\_shared\repos\pyhsslms\pyhsslms\hsslms.py", line 187, in main
    pyhsslms.HssLmsPrivateKey.genkey(keyname, levels=levels,
  File "C:\_shared\repos\pyhsslms\pyhsslms\pyhsslms.py", line 1182, in genkey
    prv_file.write(hss_prv.serialize())
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\_shared\repos\pyhsslms\pyhsslms\pyhsslms.py", line 936, in serialize
    assert self._signatures_remaining.bit_length() <= 32, "_signatures_remaining=0x%x, %d bits"%(self._signatures_remaining,self._signatures_remaining.bit_length())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: _signatures_remaining=0x200000000000, 46 bits
```

**Comment by russhousley** [comment]
The RFC does not offer a standard format for private keys.  Do you see a way to preserve backward compatibility?

**Comment by sebastien-riou** [comment]
sure, we can leverage the fact that the current implementation meet all the following conditions:
- private key file starts with `levels` encoded as a 32 bit integer in big endian convention
- `levels` >= 7 is not supported (it leads to signature_remaining being larger than 32 bits even with all other parameters sets at the 'minimum')

It follows that the current implementation crash for any private key file which starts by a non zero byte. we can therefore implement the following 'deserialize' behavior:
- first byte is 0: signature file 'version 1'
- first byte is not 0: signature file version 2 and later

we can  use the following 'serialize' behavior:
- genkey parameters supported by 'version 1', use 'version 1' serializer
- otherwise use 'version 2' serializer

The scheme outlined above allows to have newly generated private key files compatible with previous implementation as long as they are generated with parameters which were supported of course.

That said I have the feeling that such interoperability is not needed on the private key file. Private key files are supposed to be private and therefore there is no interoperability goal. We need to have newer versions able to use old private key files but I do not really see the need for old version to be able to use private key files generated by newer versions, hence my question.

**Comment by russhousley** [comment]
I am thinking about dropping the _signatures_remaining value from the serialized HSS private key.  I can carry four zero bytes to that old private keys will still load.  Then, deserialize would need to compute the value from the subordinate trees.  Thoughts?

**Comment by sebastien-riou** [comment]
I like that idea but I have no clue how to do it.
If that computation is reasonably fast that would solve elegantly the problem as far as I understand.
