### ISSUE TITLE
Incorrect implementation of LMOTS private key generation

### ISSUE THREAD

**Issue by libo-wu** [russhousley/pyhsslms#7]
I notice the implementation of LmotsPrivateKey is not consistent with RFC8554. 
In `class LmotsPrivateKey`, the publicKey() method and sign() method use `H(alg, self.S + u16(i+1) + D_PRG + self.SEED, n)` to calculate the psudorandom x_q[i].
```
def publicKey(self): 
        alg, n, p, w, ls = lmots_params[self.type]
        hash = H_start(alg)
        H_update(hash, self.S + D_PBLC)
        for i in range(0, p):
            tmp = H(alg, self.S + u16(i+1) + D_PRG + self.SEED, n)
            for j in range(0, (2**w)-1):
                tmp = H(alg, self.S + u16(i) + u8(j) + tmp, n)
            H_update(hash, tmp)
        return LmotsPublicKey(self.S, H_finish(hash, n), self.type)
```
However, in RFC 8554, x_q[i] = H(I || u32str(q) || u16str(i) || u8str(0xff) || SEED). 

The `i` here is different from your implementation.

**Comment by russhousley** [comment]
I am not sure how interoperability with the other HSS/LMS implementations is happening?  Have you explored that?

**Comment by libo-wu** [comment]
yes, I verified this in 2 repos. 
1. in Python package https://pypi.org/project/hsslms/, it uses `H(self.I + u32str(self.q) + u16str(i) + b'\xff' + SEED)` to calculate x[i].
2. in hash-sig C code (https://github.com/cisco/hash-sigs, the reference code of RFC8554), it also uses `I + q + i + 0xff + SEED`
```
unsigned char buf[ ITER_MAX_LEN ];
    memcpy( buf + ITER_I, I, I_LEN );
    put_bigendian( buf + ITER_Q, q, 4 );
    union hash_context ctx;

    hss_seed_derive_set_j( seed, 0 );

    for (i=0; i<p; i++) {
        hss_seed_derive( buf + ITER_PREV, seed, i < p-1 );
        put_bigendian( buf + ITER_K, i, 2 );
        /* We'll place j in the buffer below */
        for (j=0; j < (1<<w) - 1; j++) {
            buf[ITER_J] = j;

            hss_hash_ctx( buf + ITER_PREV, h, &ctx, buf, ITER_LEN(n) );
        }
        /* Include that in the hash */
        hss_update_hash_context(h, &public_ctx, buf + ITER_PREV, n );
    }
```

**Comment by libo-wu** [comment]
The sign-verify with other implementation has no issue. For example, I sign msg with pyhsslms, the verification with other library passes. And vice versa.

This is because the verify has nothing to do with the private components. As long as the calculated tree root value matches with the publickey, then the signature is verified.

However, the public key derivation from the SEED and I is not the same between pyhsslms and other implementations.

**Comment by russhousley** [comment]
I see the concern that you are raising, I will need to look into backward compatibility issues.
